// Generated by IB v0.4.7 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation TodoController
@end

@implementation ToDosController
@end

@implementation ToDo
@end

