// Generated by IB v0.4.7 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface TodoController: UIViewController

@property IBOutlet UITextField * nameField;
@property IBOutlet UITextView * descriptionField;

-(IBAction) textFieldDidEndEditing:(id) textField;

@end

@interface ToDosController: UITableViewController
-(IBAction) viewDidLoad;
-(IBAction) add_item;

@end

@interface ToDo: NSObject
@end

